---
title: "p8105_hw6_rq2166"
author: "Ruoyuan Qian"
date: "11/18/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(modelr)
library(mgcv)
```

```{r}
birthweight = 
  read_csv("data/birthweight.csv") %>% 
    janitor::clean_names() %>% 
    mutate(babysex = factor(babysex,level=c(1:2),
                    labels = c("male","female")),
           frace = factor(frace,level=c(1:4,8,9),
                    labels = c("White","Black",
                               "Asian","Puerto Rican",
                               "Other","Unknown")),
           malform = factor(malform,level=c(0:1),
                    labels = c("absent","present")),
           mrace = factor(mrace,level=c(1:4,8),
                    labels = c("White","Black",
                               "Asian","Puerto Rican",
                               "Other")))

anyNA(birthweight)

```
```{r}
 fit = lm(bwt~.,birthweight)
summary(fit)

variable = 
 lm(bwt~.,birthweight)%>% 
  broom::tidy() %>% 
  filter(p.value<0.05,
         !(term == "(Intercept)"))
  

 mod = lm(bwt~babysex+bhead+blength+
            delwt+gaweeks+mrace+parity+smoken,
          birthweight)
summary(mod)

```
```{r}

birthweight %>% 
  add_predictions(mod) %>% 
  add_residuals(mod) %>% 
  ggplot(aes(x = pred, y = resid)) + geom_point(alpha = .3,color = "blue") + 
  geom_smooth(aes(y = resid), color = "red",method = "lm")
```
```{r}
 mod_1 = lm(bwt~blength + gaweeks,birthweight)
 mod_2 = lm(bwt~bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex ,birthweight)

```

```{r}
cv_df = 
  crossv_mc(birthweight, 100) 

cv_df %>% pull(train) %>% .[[1]] %>% as_tibble

cv_df =
  cv_df %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))


```
```{r}
cv_df = 
  cv_df %>% 
  mutate(mod_diy  =
           map(train,~lm(bwt~babysex+bhead+blength+delwt+gaweeks+mrace+parity+smoken,data = .x)),
         mod_1  = 
           map(train, ~lm(bwt~blength + gaweeks, data = .x)),
         mod_2  = 
           map(train, ~lm(bwt~bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex ,data = .x))) %>% 
  mutate(rmse_diy = map2_dbl(mod_diy, test, ~rmse(model = .x, data = .y)),
         rmse_1 = map2_dbl(mod_1, test, ~rmse(model = .x, data = .y)),
         rmse_2 = map2_dbl(mod_2, test, ~rmse(model = .x, data = .y)))
```
```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

# Problem 2
```{r}
weather_df =
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"),
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather = 
  weather_df %>% 
  select(tmax,tmin)



```

```{r}
#boot_straps = 
#  weather %>% 
#  modelr::bootstrap(n = 1000)

#as_data_frame(boot_straps$strap[[1]])

#a = lm( tmax ~ tmin , data = weather) 
#summary(a)
#tidy = broom::tidy(a)
#b1 * b2
#prod(tidy[[2]])

# r2
#broom::glance(a)[[1]]

estimate = 
  weather %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm( tmax ~ tmin , data = .x) ),
    results = map(models, broom::tidy),
    glance = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(results,glance) %>% 
  group_by(.id) %>% 
  mutate( log_b = log(prod(estimate))) %>% 
  ungroup(.id) %>% 
  select(r.squared,log_b) %>% 
  unique()

```

```{r}
estimate %>% 
  ggplot(aes(r.squared,..density..))+
 geom_histogram()+
 geom_line(stat = 'Density',size = 1)+
    labs(x = "R squared",
         title = "Plot 1  Distribution of R squared")

estimate %>% 
  ggplot(aes(log_b,..density..))+
 geom_histogram()+
 geom_line(stat = 'Density',size = 1)+
    labs(x = "log(bea_1 * beta_2)",
         title = "Plot 2  Distribution of log(bea_1 * beta_2)")
```

```{r}
n = 
estimate %>% 
  pull(log_b) %>% 
  length()


ci = 
estimate %>% 
  mutate(r.squared = sort(r.squared),
         ci_95_r_squared = 
           str_c(round(r.squared[0.025*n],4),
                 "-",round(r.squared[0.975*n],4)),
         log_b = sort(log_b),
         ci_95_log_b =
           str_c(round(log_b[0.025*n],4),
                 "-",
                 round(log_b[0.975*n],4))) %>% 
  select(-r.squared,-log_b) %>% 
    unique() %>% 
  pivot_longer(ci_95_r_squared:
               ci_95_log_b,
               names_prefix = "ci_95_",
               names_to = "variable",
               values_to = "CI") 

ci
```

